site:
  title: Coderic Documentación
  start_page: ROOT::index.adoc
  robots: disallow
content:
  sources: 
  - url: .
    branches: gh-pages
    start_path: ROOT

ui: 
  bundle:
    url: https://coderic.github.io/theme-docs/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-component-sort-order: ROOT,development,crowdfunding,coworking,freelancers,learning,community
antora:
  extensions:
  - '@antora/lunr-extension'
